version: '3'

services:
   mysql:
     image: mysql:5.7
     deploy:
        replicas: 2
     volumes:
       - /root/Test/volume:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: abc123

   wordpress:
     depends_on:
       - mysql
     image: wordpress:latest
     volumes:
       - /root/Test/wordpress_data:/var/www/html
     deploy:
        replicas: 2
     ports:
       - "80:80"
     environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: abc123
volumes:
    db_data:
